# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 171dd1035a1979254ebd379877742b600eaaa1a2649112979133a2fe5613f58a9feb8b649f5ac279c86a5bce3a9fd655bf8fce7536a3f369c8fbd8510fb4e6ff

test:
  secret_key_base: 0f8349c41e622ecc80e4c968978002d67d640d7c6248928d48c03055461d428864fffcb979d31e891d93d29d4460bdcb06230d00cd15386f494daaf90cb01564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
